Users are persons
radicle-dev/radicle-link pull request #423
Opened 2020-11-16 16:29 UTC by kim

Fixes #419

2020-11-16 17:29 UTC, FintanH requested changes
There's mention of "users" in the identity resolution doc as well, for example in the second paragraph here https://github.com/radicle-dev/radicle-link/blob/user-is-person/docs/rfc/identity_resolution.md#motivation. It would make sense to keep that in line with the change in language here.

2020-11-16 17:29 UTC, FintanH commented on librad/src/identities/payload.rs
> +    fn gen_user_payload() -> impl Strategy<Value = PersonPayload> {
Dunno how far you want to go with renaming, but the function names still mention `user`
```suggestion
    fn gen_person_payload() -> impl Strategy<Value = PersonPayload> {
```

2020-11-16 17:29 UTC, FintanH commented on librad/src/identities/payload.rs
> +    fn gen_user_delegations() -> impl Strategy<Value = PersonDelegations> {
Here too:
```suggestion
    fn gen_person_delegations() -> impl Strategy<Value = PersonDelegations> {
```

2020-11-16 17:29 UTC, FintanH commented on librad/src/identities/git.rs
> +    pub fn as_user(&self) -> Identities<'_, Person> {
```suggestion
    pub fn as_person(&self) -> Identities<'_, Person> {
```

2020-11-16 17:29 UTC, FintanH commented on librad/src/identities/git.rs
>      fn updated_user(
```suggestion
    fn updated_person(
```

2020-11-17 09:38 UTC, kim commented
> in the identity resolution doc

Yaah, but that also uses "entities" -- as that is not "official specification", I'd rather leave it as is. I've updated [identities.md](./docs/spec/identities.md)

2020-11-17 09:39 UTC, kim commented
I also left seed stuff untouched. Not sure... that seems more like an "upstream server" at the moment.

2020-11-17 09:40 UTC, FintanH commented
> Yaah, but that also uses "entities" -- as that is not "official specification", I'd rather leave it as is. I've updated identities.md

Fair enough :+1: I can rework it to make it more official at some point :)

2020-11-17 09:40 UTC, FintanH submitted a review, later dismissed
I persist therefore I am

2020-11-18 08:22 UTC, xla approved these changes
🏮 🕷 🔧 ☑️

2020-11-18 09:18 UTC, FintanH approved these changes
I'm persistent therefore I am

2020-11-18 09:27 UTC, merged