Update copyright and add DCO
radicle-dev/radicle-link pull request #455
Opened 2020-11-27 14:16 UTC by cloudhead

2020-11-27 14:17 UTC, cloudhead commented
Is there an easy way to update all license headers?

2020-11-27 15:14 UTC, FintanH requested changes

2020-11-27 15:14 UTC, FintanH commented on LICENSE
> +                   Developer Certificate of Origin
The DCO should be in a separate file

2020-11-27 15:14 UTC, FintanH commented on .license-header
> +// Copyright (C) 2019-2020 The Radicle Foundation <hello@radicle.foundation>
I believe we're minimising what needs to go in the header. @angedupre said she would get back to me on a shorter copy for it.

2020-11-27 15:14 UTC, FintanH commented
> Is there an easy way to update all license headers? /cc @FintanH

Not that I know. Maybe a migration `sed` script :smile:

2020-11-30 09:54 UTC, kim commented
This one worked for me:

```shell
find . -name '*.rs' -print0 | xargs -0 sed -i -e '/\/\/ This file is part of radicle-link/,/\/\/ along with this program/c\
// Copyright © 2019-2020 The Radicle Foundation <hello@radicle.foundation>\
//\
// This file is part of radicle-link, distributed under the GPLv3 with Radicle\
// Linking Exception. For full terms see the included LICENSE file.'
```

It's not idempotent though

2020-11-30 10:16 UTC, kim commented
@cloudhead PTAL

2020-11-30 10:17 UTC, kim approved these changes

2020-11-30 10:24 UTC, merged